// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.data;

namespace app.data.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("app.entity.AnamnezForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float?>("BasenÖlcüsü")
                        .HasColumnType("real");

                    b.Property<float?>("BelÖlcüsü")
                        .HasColumnType("real");

                    b.Property<float?>("Boy")
                        .HasColumnType("real");

                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.Property<float?>("GögüsÖlcüsü")
                        .HasColumnType("real");

                    b.Property<float?>("Kilo")
                        .HasColumnType("real");

                    b.Property<string>("Soru1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Soru17")
                        .HasColumnType("int");

                    b.Property<int?>("Soru18")
                        .HasColumnType("int");

                    b.Property<int?>("Soru19")
                        .HasColumnType("int");

                    b.Property<string>("Soru2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Soru20")
                        .HasColumnType("int");

                    b.Property<int?>("Soru21")
                        .HasColumnType("int");

                    b.Property<int?>("Soru22")
                        .HasColumnType("int");

                    b.Property<int?>("Soru23")
                        .HasColumnType("int");

                    b.Property<int?>("Soru24")
                        .HasColumnType("int");

                    b.Property<string>("Soru25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soru9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Yas")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DietId")
                        .IsUnique();

                    b.ToTable("AnamnezForms");
                });

            modelBuilder.Entity("app.entity.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("int");

                    b.Property<string>("CurrentHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentMounth")
                        .HasColumnType("int");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("int");

                    b.Property<int?>("DietWekklyId")
                        .HasColumnType("int");

                    b.Property<int>("FinishedHour")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartingHour")
                        .HasColumnType("int");

                    b.Property<string>("Traning")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DietWekklyId")
                        .IsUnique()
                        .HasFilter("[DietWekklyId] IS NOT NULL");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("app.entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("app.entity.CombineDietMenüRecipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("DietMenüId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "DietMenüId");

                    b.HasIndex("DietMenüId");

                    b.ToTable("CombineDietMenüRecipe");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            DietMenüId = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            DietMenüId = 1
                        },
                        new
                        {
                            RecipeId = 4,
                            DietMenüId = 2
                        },
                        new
                        {
                            RecipeId = 1,
                            DietMenüId = 3
                        },
                        new
                        {
                            RecipeId = 6,
                            DietMenüId = 4
                        },
                        new
                        {
                            RecipeId = 4,
                            DietMenüId = 5
                        },
                        new
                        {
                            RecipeId = 7,
                            DietMenüId = 5
                        },
                        new
                        {
                            RecipeId = 5,
                            DietMenüId = 5
                        },
                        new
                        {
                            RecipeId = 5,
                            DietMenüId = 6
                        },
                        new
                        {
                            RecipeId = 7,
                            DietMenüId = 6
                        },
                        new
                        {
                            RecipeId = 6,
                            DietMenüId = 7
                        },
                        new
                        {
                            RecipeId = 4,
                            DietMenüId = 8
                        },
                        new
                        {
                            RecipeId = 3,
                            DietMenüId = 8
                        },
                        new
                        {
                            RecipeId = 1,
                            DietMenüId = 9
                        },
                        new
                        {
                            RecipeId = 2,
                            DietMenüId = 10
                        });
                });

            modelBuilder.Entity("app.entity.CombineDietRecipe", b =>
                {
                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("DietId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("CombineDietRecipe");

                    b.HasData(
                        new
                        {
                            DietId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            DietId = 1,
                            RecipeId = 2
                        },
                        new
                        {
                            DietId = 1,
                            RecipeId = 3
                        },
                        new
                        {
                            DietId = 2,
                            RecipeId = 4
                        },
                        new
                        {
                            DietId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            DietId = 2,
                            RecipeId = 2
                        });
                });

            modelBuilder.Entity("app.entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemaningDietPackages")
                        .HasColumnType("int");

                    b.Property<int>("RemaningPilatesPackages")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Dilek",
                            Gender = true,
                            LastName = "Karaca",
                            Mail = "dlk@gmail.com",
                            PhoneNumber = "5524673747",
                            RemaningDietPackages = 0,
                            RemaningPilatesPackages = 0,
                            UserId = "asdad"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sinem",
                            Gender = true,
                            LastName = "Karaca",
                            Mail = "dlk@gmail.com",
                            PhoneNumber = "5524673747",
                            RemaningDietPackages = 0,
                            RemaningPilatesPackages = 0,
                            UserId = "asdad"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Muammer",
                            Gender = false,
                            LastName = "Karaca",
                            Mail = "dlk@gmail.com",
                            PhoneNumber = "5524673747",
                            RemaningDietPackages = 0,
                            RemaningPilatesPackages = 0,
                            UserId = "asdad"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ercan",
                            Gender = false,
                            LastName = "Karaca",
                            Mail = "dlk@gmail.com",
                            PhoneNumber = "5524673747",
                            RemaningDietPackages = 0,
                            RemaningPilatesPackages = 0,
                            UserId = "asdad"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Mustafa",
                            Gender = false,
                            LastName = "Karaca",
                            Mail = "dlk@gmail.com",
                            PhoneNumber = "5524673747",
                            RemaningDietPackages = 0,
                            RemaningPilatesPackages = 0,
                            UserId = "asdad"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Sercan",
                            Gender = false,
                            LastName = "Karaca",
                            Mail = "dlk@gmail.com",
                            PhoneNumber = "5524673747",
                            RemaningDietPackages = 0,
                            RemaningPilatesPackages = 0,
                            UserId = "asdad"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Güven",
                            Gender = false,
                            LastName = "Karaca",
                            Mail = "dlk@gmail.com",
                            PhoneNumber = "5524673747",
                            RemaningDietPackages = 0,
                            RemaningPilatesPackages = 0,
                            UserId = "asdad"
                        });
                });

            modelBuilder.Entity("app.entity.DateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTİme")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekId")
                        .HasColumnType("int");

                    b.Property<int>("typeOfRequest")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("dateRequests");
                });

            modelBuilder.Entity("app.entity.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("StartingBreastSize")
                        .HasColumnType("int");

                    b.Property<int>("StartingWaistline")
                        .HasColumnType("int");

                    b.Property<int>("StartingWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DateEnd = new DateTime(2021, 6, 21, 0, 45, 26, 828, DateTimeKind.Local).AddTicks(1204),
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 828, DateTimeKind.Local).AddTicks(9991),
                            Height = 168,
                            StartingBreastSize = 84,
                            StartingWaistline = 90,
                            StartingWeight = 80
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DateEnd = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1859),
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1866),
                            Height = 168,
                            StartingBreastSize = 84,
                            StartingWaistline = 90,
                            StartingWeight = 80
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            DateEnd = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1869),
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1871),
                            Height = 168,
                            StartingBreastSize = 84,
                            StartingWaistline = 90,
                            StartingWeight = 80
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            DateEnd = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1872),
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1874),
                            Height = 168,
                            StartingBreastSize = 84,
                            StartingWaistline = 90,
                            StartingWeight = 80
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            DateEnd = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1876),
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1877),
                            Height = 168,
                            StartingBreastSize = 84,
                            StartingWaistline = 90,
                            StartingWeight = 80
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            DateEnd = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1878),
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1879),
                            Height = 168,
                            StartingBreastSize = 84,
                            StartingWaistline = 90,
                            StartingWeight = 80
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            DateEnd = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1881),
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 829, DateTimeKind.Local).AddTicks(1882),
                            Height = 168,
                            StartingBreastSize = 84,
                            StartingWaistline = 90,
                            StartingWeight = 80
                        });
                });

            modelBuilder.Entity("app.entity.DietMenü", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DietWekklyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoMeals")
                        .HasColumnType("bit");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DietWekklyId")
                        .IsUnique();

                    b.ToTable("DietMenüs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DietWekklyId = 1,
                            FullName = "Muammer Karaca",
                            Gender = false,
                            TwoMeals = false,
                            Weight = 80
                        },
                        new
                        {
                            Id = 2,
                            DietWekklyId = 2,
                            FullName = "Sinem Karaca",
                            Gender = true,
                            TwoMeals = false,
                            Weight = 80
                        },
                        new
                        {
                            Id = 3,
                            DietWekklyId = 3,
                            FullName = "Muammer Karaca",
                            Gender = false,
                            TwoMeals = false,
                            Weight = 65
                        },
                        new
                        {
                            Id = 4,
                            DietWekklyId = 4,
                            FullName = "Sinem Karaca",
                            Gender = true,
                            TwoMeals = false,
                            Weight = 75
                        },
                        new
                        {
                            Id = 5,
                            DietWekklyId = 5,
                            FullName = "Muammer Karaca",
                            Gender = true,
                            TwoMeals = true,
                            Weight = 80
                        },
                        new
                        {
                            Id = 6,
                            DietWekklyId = 6,
                            FullName = "Dilek Karaca",
                            Gender = false,
                            TwoMeals = true,
                            Weight = 60
                        },
                        new
                        {
                            Id = 7,
                            DietWekklyId = 7,
                            FullName = "Sercan Karaca",
                            Gender = false,
                            TwoMeals = true,
                            Weight = 65
                        },
                        new
                        {
                            Id = 8,
                            DietWekklyId = 8,
                            FullName = "Muammer Karaca",
                            Gender = true,
                            TwoMeals = false,
                            Weight = 80
                        },
                        new
                        {
                            Id = 9,
                            DietWekklyId = 9,
                            FullName = "Muammer Karaca",
                            Gender = true,
                            TwoMeals = true,
                            Weight = 70
                        },
                        new
                        {
                            Id = 10,
                            DietWekklyId = 10,
                            FullName = "Sercan Karaca",
                            Gender = true,
                            TwoMeals = false,
                            Weight = 80
                        });
                });

            modelBuilder.Entity("app.entity.DietWekkly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AvgNmbrOfSteps")
                        .HasColumnType("int");

                    b.Property<double>("AvgWater")
                        .HasColumnType("float");

                    b.Property<int>("CurrentBreastSize")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWaistline")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("DateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Detox")
                        .HasColumnType("bit");

                    b.Property<int?>("DietId")
                        .HasColumnType("int");

                    b.Property<int>("DietImplementation")
                        .HasColumnType("int");

                    b.Property<bool>("GivedDate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DietId");

                    b.ToTable("DietWekklies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            AvgNmbrOfSteps = 2500,
                            AvgWater = 2.5,
                            CurrentBreastSize = 70,
                            CurrentWaistline = 80,
                            CurrentWeight = 80,
                            Detox = true,
                            DietId = 1,
                            DietImplementation = 4,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "1. Hafta"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            AvgNmbrOfSteps = 2700,
                            AvgWater = 2.0,
                            CurrentBreastSize = 68,
                            CurrentWaistline = 79,
                            CurrentWeight = 78,
                            Detox = true,
                            DietId = 1,
                            DietImplementation = 3,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "2. Hafta"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            AvgNmbrOfSteps = 2300,
                            AvgWater = 3.0,
                            CurrentBreastSize = 67,
                            CurrentWaistline = 76,
                            CurrentWeight = 75,
                            Detox = true,
                            DietId = 1,
                            DietImplementation = 2,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "3. Hafta"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            AvgNmbrOfSteps = 200,
                            AvgWater = 2.0,
                            CurrentBreastSize = 65,
                            CurrentWaistline = 75,
                            CurrentWeight = 60,
                            Detox = true,
                            DietId = 1,
                            DietImplementation = 5,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "4. Hafta"
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            AvgNmbrOfSteps = 2500,
                            AvgWater = 2.5,
                            CurrentBreastSize = 70,
                            CurrentWaistline = 80,
                            CurrentWeight = 80,
                            Detox = true,
                            DietId = 2,
                            DietImplementation = 4,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "1. Hafta"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            AvgNmbrOfSteps = 2700,
                            AvgWater = 2.0,
                            CurrentBreastSize = 68,
                            CurrentWaistline = 79,
                            CurrentWeight = 78,
                            Detox = true,
                            DietId = 2,
                            DietImplementation = 3,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "2. Hafta"
                        },
                        new
                        {
                            Id = 7,
                            Active = false,
                            AvgNmbrOfSteps = 2300,
                            AvgWater = 3.0,
                            CurrentBreastSize = 67,
                            CurrentWaistline = 76,
                            CurrentWeight = 75,
                            Detox = true,
                            DietId = 2,
                            DietImplementation = 2,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "3. Hafta"
                        },
                        new
                        {
                            Id = 8,
                            Active = false,
                            AvgNmbrOfSteps = 200,
                            AvgWater = 2.0,
                            CurrentBreastSize = 65,
                            CurrentWaistline = 75,
                            CurrentWeight = 60,
                            Detox = true,
                            DietId = 2,
                            DietImplementation = 5,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "4. Hafta"
                        },
                        new
                        {
                            Id = 9,
                            Active = false,
                            AvgNmbrOfSteps = 2500,
                            AvgWater = 2.5,
                            CurrentBreastSize = 70,
                            CurrentWaistline = 80,
                            CurrentWeight = 80,
                            Detox = true,
                            DietId = 3,
                            DietImplementation = 4,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "1. Hafta"
                        },
                        new
                        {
                            Id = 10,
                            Active = false,
                            AvgNmbrOfSteps = 2700,
                            AvgWater = 2.0,
                            CurrentBreastSize = 68,
                            CurrentWaistline = 79,
                            CurrentWeight = 78,
                            Detox = true,
                            DietId = 3,
                            DietImplementation = 3,
                            GivedDate = false,
                            IsUpdate = false,
                            Name = "2. Hafta"
                        });
                });

            modelBuilder.Entity("app.entity.GeneralMesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlertType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("href")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GeneralMesajs");
                });

            modelBuilder.Entity("app.entity.MyCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("PaidType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("MyCarts");
                });

            modelBuilder.Entity("app.entity.PackageRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("typeOfRequest")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("packageRequests");
                });

            modelBuilder.Entity("app.entity.Pilates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Pilateis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 832, DateTimeKind.Local).AddTicks(9446)
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 833, DateTimeKind.Local).AddTicks(117)
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 833, DateTimeKind.Local).AddTicks(122)
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 833, DateTimeKind.Local).AddTicks(124)
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 833, DateTimeKind.Local).AddTicks(125)
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 833, DateTimeKind.Local).AddTicks(127)
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            DateStart = new DateTime(2021, 6, 21, 0, 45, 26, 833, DateTimeKind.Local).AddTicks(128)
                        });
                });

            modelBuilder.Entity("app.entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("app.entity.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Salata Tarifi"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Name = "Kabak Tarifi"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Name = "Tuzlu Tarifi"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Name = "Omlet Tarifi"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Name = "Su Tarifi"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Name = "Kahve Tarifi"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Name = "Karnıbahar Tarifi"
                        });
                });

            modelBuilder.Entity("app.entity.AnamnezForm", b =>
                {
                    b.HasOne("app.entity.Diet", "Diet")
                        .WithOne("AnamnezForm")
                        .HasForeignKey("app.entity.AnamnezForm", "DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");
                });

            modelBuilder.Entity("app.entity.Calendar", b =>
                {
                    b.HasOne("app.entity.DietWekkly", "DietWekkly")
                        .WithOne("Calendar")
                        .HasForeignKey("app.entity.Calendar", "DietWekklyId");

                    b.Navigation("DietWekkly");
                });

            modelBuilder.Entity("app.entity.CombineDietMenüRecipe", b =>
                {
                    b.HasOne("app.entity.DietMenü", "DietMenü")
                        .WithMany("CombineDietMenüRecipes")
                        .HasForeignKey("DietMenüId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.entity.Recipe", "Recipe")
                        .WithMany("CombineDietMenüRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietMenü");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("app.entity.CombineDietRecipe", b =>
                {
                    b.HasOne("app.entity.Diet", "Diet")
                        .WithMany("CombineDietRecipes")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.entity.Recipe", "Recipe")
                        .WithMany("CombineDietRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("app.entity.Diet", b =>
                {
                    b.HasOne("app.entity.Customer", "Customer")
                        .WithOne("Diet")
                        .HasForeignKey("app.entity.Diet", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("app.entity.DietMenü", b =>
                {
                    b.HasOne("app.entity.DietWekkly", "DietWekkly")
                        .WithOne("DietMenü")
                        .HasForeignKey("app.entity.DietMenü", "DietWekklyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietWekkly");
                });

            modelBuilder.Entity("app.entity.DietWekkly", b =>
                {
                    b.HasOne("app.entity.Diet", "Diet")
                        .WithMany("DietWekklies")
                        .HasForeignKey("DietId");

                    b.Navigation("Diet");
                });

            modelBuilder.Entity("app.entity.MyCart", b =>
                {
                    b.HasOne("app.entity.Customer", "customer")
                        .WithMany("MyCarts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("app.entity.Pilates", b =>
                {
                    b.HasOne("app.entity.Customer", "Customer")
                        .WithOne("Pilates")
                        .HasForeignKey("app.entity.Pilates", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("app.entity.Product", b =>
                {
                    b.HasOne("app.entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("app.entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("app.entity.Customer", b =>
                {
                    b.Navigation("Diet");

                    b.Navigation("MyCarts");

                    b.Navigation("Pilates");
                });

            modelBuilder.Entity("app.entity.Diet", b =>
                {
                    b.Navigation("AnamnezForm");

                    b.Navigation("CombineDietRecipes");

                    b.Navigation("DietWekklies");
                });

            modelBuilder.Entity("app.entity.DietMenü", b =>
                {
                    b.Navigation("CombineDietMenüRecipes");
                });

            modelBuilder.Entity("app.entity.DietWekkly", b =>
                {
                    b.Navigation("Calendar");

                    b.Navigation("DietMenü");
                });

            modelBuilder.Entity("app.entity.Recipe", b =>
                {
                    b.Navigation("CombineDietMenüRecipes");

                    b.Navigation("CombineDietRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
